"""add property_id to notifications

Revision ID: 676079d0a449
Revises: ee103280906c
Create Date: 2026-07-31 15:07:49.454891

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676079d0a449'
down_revision: Union[str, None] = 'ee103280906c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('property_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_notifications_property_id'), 'notifications', ['property_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_property_id'), table_name='notifications')
    op.drop_column('notifications', 'property_id')
    # ### end Alembic commands ###
