"""add_refundable_amount_to_rooms

Revision ID: 8491d42b66d8
Revises: 023_referral_code
Create Date: 2026-06-04 13:17:46.582176

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8491d42b66d8'
down_revision: Union[str, None] = '023_referral_code'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.engine.reflection import Inspector
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('rooms')]
    if 'refundable_amount' not in columns:
        op.add_column('rooms', sa.Column('refundable_amount', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'refundable_amount')
    # ### end Alembic commands ###
