"""add city notifications table

Revision ID: ee103280906c
Revises: d44e34d66322
Create Date: 2026-07-27 13:42:20.646850

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee103280906c'
down_revision: Union[str, None] = 'd44e34d66322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('property_comparisons')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user', table_name='audit_logs')
    op.drop_index('idx_bookings_customer', table_name='bookings')
    op.drop_index('idx_bookings_owner', table_name='bookings')
    op.drop_index('idx_bookings_status', table_name='bookings')
    op.drop_index('idx_favorites_user', table_name='favorites')
    op.drop_index('idx_messages_from', table_name='messages')
    op.drop_index('idx_messages_to', table_name='messages')
    op.drop_index('idx_notification_logs_created', table_name='notification_logs')
    op.drop_index('idx_notification_logs_user_type', table_name='notification_logs')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_index('idx_properties_city', table_name='properties')
    op.drop_index('idx_properties_gender', table_name='properties')
    op.drop_index('idx_properties_owner', table_name='properties')
    op.drop_index('idx_properties_status', table_name='properties')
    op.drop_index('idx_reviews_property', table_name='reviews')
    op.drop_index('idx_system_settings_key', table_name='system_settings')
    op.drop_index('idx_transaction_otps_transaction', table_name='transaction_otps')
    op.drop_index('idx_wallet_transactions_booking', table_name='wallet_transactions')
    op.drop_index('idx_wallet_transactions_payer', table_name='wallet_transactions')
    op.drop_index('idx_wallet_transactions_receiver', table_name='wallet_transactions')
    op.drop_index('idx_wallet_transactions_status', table_name='wallet_transactions')
    op.drop_index('idx_wallet_transactions_wallet', table_name='wallet_transactions')
    op.drop_index('idx_wallets_user', table_name='wallets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_wallets_user', 'wallets', ['user_id'], unique=False)
    op.create_index('idx_wallet_transactions_wallet', 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_index('idx_wallet_transactions_status', 'wallet_transactions', ['status'], unique=False)
    op.create_index('idx_wallet_transactions_receiver', 'wallet_transactions', ['receiver_id'], unique=False)
    op.create_index('idx_wallet_transactions_payer', 'wallet_transactions', ['payer_id'], unique=False)
    op.create_index('idx_wallet_transactions_booking', 'wallet_transactions', ['booking_id'], unique=False)
    op.create_index('idx_transaction_otps_transaction', 'transaction_otps', ['transaction_id'], unique=False)
    op.create_index('idx_system_settings_key', 'system_settings', ['key'], unique=False)
    op.create_index('idx_reviews_property', 'reviews', ['property_id'], unique=False)
    op.create_index('idx_properties_status', 'properties', ['status'], unique=False)
    op.create_index('idx_properties_owner', 'properties', ['owner_id'], unique=False)
    op.create_index('idx_properties_gender', 'properties', ['gender_preference'], unique=False)
    op.create_index('idx_properties_city', 'properties', ['city'], unique=False)
    op.create_index('idx_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notification_logs_user_type', 'notification_logs', ['user_id', 'notification_type'], unique=False)
    op.create_index('idx_notification_logs_created', 'notification_logs', ['created_at'], unique=False)
    op.create_index('idx_messages_to', 'messages', ['to_user'], unique=False)
    op.create_index('idx_messages_from', 'messages', ['from_user'], unique=False)
    op.create_index('idx_favorites_user', 'favorites', ['user_id'], unique=False)
    op.create_index('idx_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('idx_bookings_owner', 'bookings', ['owner_id'], unique=False)
    op.create_index('idx_bookings_customer', 'bookings', ['customer_id'], unique=False)
    op.create_index('idx_audit_logs_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_table('property_comparisons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='property_comparisons_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='property_comparisons_pkey')
    )
    op.drop_table('city_notifications')
    # ### end Alembic commands ###
